// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiMimZfl7y3erqKn5B8bruIuraxWjL7Nk',
    appId: '1:442811814265:web:185a722dc1445b91531fa8',
    messagingSenderId: '442811814265',
    projectId: 'flutter-af29a',
    authDomain: 'flutter-af29a.firebaseapp.com',
    storageBucket: 'flutter-af29a.firebasestorage.app',
    measurementId: 'G-BT8FD453EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCDw1kl3QpC8ELWtmTKspX8nPP91xgtLY',
    appId: '1:442811814265:android:9dae9f0e79d39a15531fa8',
    messagingSenderId: '442811814265',
    projectId: 'flutter-af29a',
    storageBucket: 'flutter-af29a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCACJj0wYzoxB_fJ6X_ObJLkn0uqePkqJM',
    appId: '1:442811814265:ios:8fc04f4c458f0c67531fa8',
    messagingSenderId: '442811814265',
    projectId: 'flutter-af29a',
    storageBucket: 'flutter-af29a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCACJj0wYzoxB_fJ6X_ObJLkn0uqePkqJM',
    appId: '1:442811814265:ios:8fc04f4c458f0c67531fa8',
    messagingSenderId: '442811814265',
    projectId: 'flutter-af29a',
    storageBucket: 'flutter-af29a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiMimZfl7y3erqKn5B8bruIuraxWjL7Nk',
    appId: '1:442811814265:web:67bfddfe4b01cd5a531fa8',
    messagingSenderId: '442811814265',
    projectId: 'flutter-af29a',
    authDomain: 'flutter-af29a.firebaseapp.com',
    storageBucket: 'flutter-af29a.firebasestorage.app',
    measurementId: 'G-GQ9E013WB2',
  );
}
